const mockProducts = [

    {
      id: 1,
      name: "Nike Air Max 270 React",
      price: 599.43,
      discountPrice: 299.43,
      discountPercent: 50,
      ratingValue: 4.5,
      ratingCount: 28,
      isHot: true,
      colors: ["#000000", "#FF0000", "#0000FF", "#FFFF00"],
      category: "Sneakers",
      brand: "Nike",
      imageUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1071f868-fb24-4d88-aa7d-b97d632a1ff8/W+AIR+MAX+270.png",
    },
    {
      id: 2,
      name: "Nike Air Max 270 React",
      price: 534.33,
      discountPrice: 299.43,
      discountPercent: 44,
      ratingValue: 4.2,
      ratingCount: 55,
      isHot: true,
      colors: ["#FF0000", "#C0C0C0"],
      category: "Handbags",
      brand: "Nike",
      imageUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/przhlilttuqiis7no3rr/W+AIR+MAX+270.png",
    },
    {
      id: 3,
      name: "Nike Air Max 270 React",
      price: 994.99,
      discountPrice: 299.43,
      discountPercent: 70,
      ratingValue: 4.8,
      ratingCount: 102,
      isHot: true,
      colors: ["#F5DEB3", "#FFFFFF"],
      category: "Accessories",
      brand: "Adidas",
      imageUrl: "https://www.superkicks.in/cdn/shop/products/270r.jpg?v=1675953655",
    },
    {
      id: 4,
      name: "Adidas Ultraboost",
      price: 220.0,
      discountPrice: 180.0,
      discountPercent: 18,
      ratingValue: 4.9,
      ratingCount: 250,
      isHot: false,
      colors: ["#FFFFFF", "#000000"],
      category: "Running",
      brand: "Adidas",
      imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQVmVFJ2do394xaSe3Q-o9ccd9OnEKimuJpBzKh_iVAzmPl9349fov15S83mrahsossaMpCQKfIR32k6kZ7zMD57A1dXYxGZS1-GPm_mAIsW8F3jiIAAcXK9Q",
    },
    {
      id: 5,
      name: "Vans Old Skool",
      price: 75.0,
      discountPrice: 60.0,
      discountPercent: 20,
      ratingValue: 4.7,
      ratingCount: 500,
      isHot: true,
      colors: ["#000000", "#FF0000", "#FFFFFF"],
      category: "Skate",
      brand: "Vans",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu_lSv6jdml_iQjvDZh7rSBIyLrrb-Lay5tg&s",
    },
     {
      id: 6,
      name: "Nike Air Max 270 React",
      price: 534.33,
      discountPrice: 299.43,
      discountPercent: 24,
      ratingValue: 4.5,
      ratingCount: 28,
      isHot: true,
      colors: ["#0000FF", "#00FF00"],
      category: "Sneakers",
      brand: "Nike",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmLKGI_BgCj4lL3Sv4O_168ITVehsoLrCr5Q&s",
    },
    {
      id: 7,
      name: "Nike Air Max 270 React",
      price: 534.33,
      discountPrice: 299.43,
      discountPercent: 24,
      ratingValue: 4.5,
      ratingCount: 28,
      isHot: true,
      colors: ["#FFFF00", "#FF00FF"],
      category: "Sneakers",
      brand: "Nike",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK1L0IXi6awUHJKp5b2ntWbOhd5npdW4fL1Q&s",
    },
    {
      id: 8,
      name: "Nike Air Max 270 React",
      price: 534.33,
      discountPrice: 299.43,
      discountPercent: 24,
      ratingValue: 4.5,
      ratingCount: 28,
      isHot: true,
      colors: ["#00FFFF", "#FFA500"],
      category: "Sneakers",
      brand: "Nike",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWNIuwN9wHLmYUYUOT0Xv5qdYMXOJHK8DGWg&s",
    },
    {
      id: 9,
      name: "Puma Suede Classic",
      price: 65.00,
      discountPrice: 55.25,
      discountPercent: 15,
      ratingValue: 4.6,
      ratingCount: 320,
      isHot: false,
      colors: ["#FF0000", "#000000", "#0000FF"],
      category: "Lifestyle",
      brand: "Puma",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ1OnRdCwaaCDwMbAk8fsNJ9yELrnQ0OCGfQ&s",
    },
    {
      id: 10,
      name: "Reebok Classic Leather",
      price: 80.00,
      discountPrice: 70.00,
      discountPercent: 12.5,
      ratingValue: 4.4,
      ratingCount: 210,
      isHot: false,
      colors: ["#FFFFFF"],
      category: "Classic",
      brand: "Reebok",
      imageUrl: "https://cdn.shopify.com/s/files/1/0862/7834/0912/files/100008494_FLT_eCom-tif.png?v=1736438127"
    },
    {
      id: 11,
      name: "Converse Chuck Taylor",
      price: 55.00,
      discountPrice: 55.00,
      discountPercent: 0,
      ratingValue: 4.8,
      ratingCount: 1200,
      isHot: true,
      colors: ["#000000", "#FFFFFF", "#FF0000"],
      category: "All Stars",
      brand: "Converse",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkxqR67WtE57ymqNww9KT-63Jz5lu3JSIQCA&s",
    },
    {
      id: 12,
      name: "New Balance 574",
      price: 90.00,
      discountPrice: 81.00,
      discountPercent: 10,
      ratingValue: 4.7,
      ratingCount: 450,
      isHot: false,
      colors: ["#808080", "#000080"],
      category: "Running",
      brand: "New Balance",
      imageUrl: "https://nb.scene7.com/is/image/NB/ml574evw_nb_02_i?$pdpflexf2$&wid=440&hei=440",
    },
    {
      id: 13,
      name: "Asics GEL-Kayano",
      price: 160.00,
      discountPrice: 128.00,
      discountPercent: 20,
      ratingValue: 4.9,
      ratingCount: 600,
      isHot: false,
      colors: ["#0000FF", "#FFFF00"],
      category: "Running",
      brand: "Asics",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFi-UBOja0DK2nFRcnCumWZ1FaHsY8-4v2yA&s",
    },
    {
      id: 14,
      name: "Fila Disruptor",
      price: 70.00,
      discountPrice: 63.00,
      discountPercent: 10,
      ratingValue: 4.3,
      ratingCount: 380,
      isHot: true,
      colors: ["#FFFFFF", "#FFC0CB"],
      category: "Lifestyle",
      brand: "Fila",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlcRupmv5HDJw08mWarDnrwSYQwC92ljVn3Q&s",
    },
    {
      id: 15,
      name: "Siemens Tech T-Shirt",
      price: 45.00,
      discountPrice: 36.00,
      discountPercent: 20,
      ratingValue: 4.5,
      ratingCount: 150,
      isHot: false,
      colors: ["#000000", "#FFFFFF", "#808080"],
      category: "Apparel",
      brand: "Siemens",
      imageUrl: "https://placehold.co/400x400/F5F5F5/333333?text=Siemens+T-Shirt",
    },
    {
      id: 16,
      name: "Siemens Smart Watch",
      price: 350.00,
      discountPrice: 297.50,
      discountPercent: 15,
      ratingValue: 4.6,
      ratingCount: 220,
      isHot: true,
      colors: ["#000000", "#C0C0C0"],
      category: "Electronics",
      brand: "Siemens",
      imageUrl: "https://manuals.plus/wp-content/uploads/2024/01/SIEMENS-GT-2-Smartwatch-featured-1.png",
    },
    {
      id: 17,
      name: 'Leather Crossbody Bag',
      price: 120.0,
      discountPrice: 90.0,
      discountPercent: 25,
      ratingValue: 4.8,
      ratingCount: 75,
      isHot: false,
      colors: ['#A52A2A', '#000000'],
      category: 'Handbags',
      brand: 'Vans',
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYTSZVopWGY3Hy8LRd8IpSe_wUKEs2GfwH3g&s',
    },
    {
      id: 18,
      name: 'Canvas Tote',
      price: 40.0,
      discountPrice: 40.0,
      discountPercent: 0,
      ratingValue: 4.5,
      ratingCount: 150,
      isHot: false,
      colors: ['#F5F5DC', '#4682B4'],
      category: 'Handbags',
      brand: 'Adidas',
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTryWY6Q_vjTesaCnF7SvV1d0SDR7YaB__za7OMyELW4g_heYaFaYU40wSRGK2U70fFQmM&usqp=CAU',
    },
    {
      id: 19,
      name: 'Gold Hoop Earrings',
      price: 85.0,
      discountPrice: 68.0,
      discountPercent: 20,
      ratingValue: 4.9,
      ratingCount: 200,
      isHot: true,
      colors: ['#FFD700'],
      category: 'Accessories',
      brand: 'Nike',
      imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw71d27b15/images/hi-res/51D3D1HNAABA00_1.jpg?sw=480&sh=480',
    },
    {
      id: 20,
      name: 'Silk Scarf',
      price: 60.0,
      discountPrice: 48.0,
      discountPercent: 20,
      ratingValue: 4.7,
      ratingCount: 90,
      isHot: false,
      colors: ['#E6E6FA', '#FF69B4'],
      category: 'Accessories',
      brand: 'Siemens',
      imageUrl: 'https://hairloveindia.com/cdn/shop/files/Navy-blue_930a171f-d16d-4005-8d56-13741a1dda9a_1200x.jpg?v=1692336203',
    },
    {
      id: 21,
      name: 'Adidas Soccer Ball',
      price: 25.0,
      discountPrice: 20.0,
      discountPercent: 20,
      ratingValue: 4.9,
      ratingCount: 800,
      isHot: false,
      colors: ['#FFFFFF', '#000000'],
      category: 'Sports',
      brand: 'Adidas',
      imageUrl: 'https://assets.adidas.com/images/w_600,f_auto,q_auto/19d2ab18db174354a47f40b61e1ce689_9366/Fussballliebe_League_Ball_White_IN9369_02_standard_hover.jpg',
    },
    {
      id: 22,
      name: 'Vans Beanie',
      price: 22.0,
      discountPrice: 22.0,
      discountPercent: 0,
      ratingValue: 4.6,
      ratingCount: 120,
      isHot: true,
      colors: ['#000000', '#800000'],
      category: 'Accessories',
      brand: 'Vans',
      imageUrl: 'https://assets.vans.com/images/t_img/c_fill,g_center,f_auto,h_573,w_458,e_unsharp_mask:100/dpr_2.0/v1752509058/VN000QAUE2V-HERO/Hex-Patch-Cuff-Beanie.png',
    },
    {
      id: 23,
      name: 'Nike Pro Hijab',
      price: 35.0,
      discountPrice: 31.5,
      discountPercent: 10,
      ratingValue: 4.9,
      ratingCount: 40,
      isHot: false,
      colors: ['#000000', '#FFFFFF', '#808080'],
      category: 'Accessories',
      brand: 'Nike',
      imageUrl: 'https://static.nike.com/a/images/f_auto,cs_srgb/w_960,c_limit/fd3f3414-9914-4546-a907-19cc2248b0cc/nike-empowers-muslim-female-athletes-with-groundbreaking-sports-hijab.jpg',
    },
    {
      id: 24,
      name: 'Siemens Industrial Phone Case',
      price: 50.0,
      discountPrice: 40.0,
      discountPercent: 20,
      ratingValue: 4.4,
      ratingCount: 85,
      isHot: false,
      colors: ['#A9A9A9', '#000000'],
      category: 'Accessories',
      brand: 'Siemens',
      imageUrl: 'https://placehold.co/400x400/F5F5F5/333333?text=Siemens+Case',
    },
  ];

export default mockProducts;